// <auto-generated />
using System;
using Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Data.CMS.Aktualnosc", b =>
                {
                    b.Property<int>("IdAktualnosci")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAktualnosci"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Pozycja")
                        .HasColumnType("int");

                    b.Property<string>("Tresc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TytulLinku")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdAktualnosci");

                    b.ToTable("Aktualnosc");
                });

            modelBuilder.Entity("Data.Data.CMS.Strona", b =>
                {
                    b.Property<int>("IdStrony")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStrony"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Pozycja")
                        .HasColumnType("int");

                    b.Property<string>("Tresc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TytulLinku")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdStrony");

                    b.ToTable("Strona");
                });

            modelBuilder.Entity("Data.Data.Magazyn.JednostkaMiary", b =>
                {
                    b.Property<int>("IdJednostki")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UomId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJednostki"));

                    b.Property<bool>("CzyAktywna")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Code");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("IdJednostki");

                    b.ToTable("UnitsOfMeasure");
                });

            modelBuilder.Entity("Data.Data.Magazyn.Kategoria", b =>
                {
                    b.Property<int>("IdKategorii")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKategorii"));

                    b.Property<int?>("IdNadrzednejKategorii")
                        .HasColumnType("int")
                        .HasColumnName("ParentCategoryId");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.Property<string>("Sciezka")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Path");

                    b.HasKey("IdKategorii");

                    b.HasIndex("IdNadrzednejKategorii");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Data.Data.Magazyn.Lokacja", b =>
                {
                    b.Property<int>("IdLokacji")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LocationId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLokacji"));

                    b.Property<bool>("CzyAktywna")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<int>("IdMagazynu")
                        .HasColumnType("int")
                        .HasColumnName("WarehouseId");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Code");

                    b.Property<string>("Opis")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Description");

                    b.HasKey("IdLokacji");

                    b.HasIndex("IdMagazynu", "Kod")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Data.Data.Magazyn.Magazyn", b =>
                {
                    b.Property<int>("IdMagazynu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WarehouseId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMagazynu"));

                    b.Property<string>("Adres")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Address");

                    b.Property<bool>("CzyAktywny")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Name");

                    b.HasKey("IdMagazynu");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("Data.Data.Magazyn.Produkt", b =>
                {
                    b.Property<int>("IdProduktu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduktu"));

                    b.Property<bool>("CzyAktywny")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<int>("IdDomyslnejJednostki")
                        .HasColumnType("int")
                        .HasColumnName("DefaultUomId");

                    b.Property<int>("IdKategorii")
                        .HasColumnType("int")
                        .HasColumnName("CategoryId");

                    b.Property<decimal?>("IloscPonownegoZamowienia")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("ReorderQty");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("SKU");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Name");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<decimal?>("PunktPonownegoZamowienia")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("ReorderPoint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<decimal>("StanMinimalny")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("MinStock");

                    b.Property<DateTime>("UtworzonoUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.HasKey("IdProduktu");

                    b.HasIndex("IdKategorii");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Data.Data.Magazyn.Rola", b =>
                {
                    b.Property<int>("IdRoli")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRoli"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("IdRoli");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Data.Data.Magazyn.RuchMagazynowy", b =>
                {
                    b.Property<int>("IdRuchu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StockMovementId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRuchu"));

                    b.Property<int?>("IdLokacjiDo")
                        .HasColumnType("int")
                        .HasColumnName("ToLocationId");

                    b.Property<int?>("IdLokacjiZ")
                        .HasColumnType("int")
                        .HasColumnName("FromLocationId");

                    b.Property<int>("IdProduktu")
                        .HasColumnType("int")
                        .HasColumnName("ProductId");

                    b.Property<int?>("IdUzytkownika")
                        .HasColumnType("int")
                        .HasColumnName("CreatedByUserId");

                    b.Property<decimal>("Ilosc")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("Quantity");

                    b.Property<string>("Notatka")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Note");

                    b.Property<string>("Referencja")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Reference");

                    b.Property<int>("Typ")
                        .HasColumnType("int")
                        .HasColumnName("MovementType");

                    b.Property<DateTime>("UtworzonoUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.HasKey("IdRuchu");

                    b.HasIndex("IdLokacjiDo");

                    b.HasIndex("IdLokacjiZ");

                    b.HasIndex("IdProduktu");

                    b.HasIndex("IdUzytkownika");

                    b.ToTable("StockMovements");
                });

            modelBuilder.Entity("Data.Data.Magazyn.StanMagazynowy", b =>
                {
                    b.Property<int>("IdStanu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StockId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStanu"));

                    b.Property<int>("IdLokacji")
                        .HasColumnType("int")
                        .HasColumnName("LocationId");

                    b.Property<int>("IdProduktu")
                        .HasColumnType("int")
                        .HasColumnName("ProductId");

                    b.Property<decimal>("Ilosc")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("Quantity");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.HasKey("IdStanu");

                    b.HasIndex("IdLokacji");

                    b.HasIndex("IdProduktu", "IdLokacji")
                        .IsUnique();

                    b.ToTable("Stock");
                });

            modelBuilder.Entity("Data.Data.Magazyn.Uzytkownik", b =>
                {
                    b.Property<int>("IdUzytkownika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUzytkownika"));

                    b.Property<bool>("CzyAktywny")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Email");

                    b.Property<string>("HashHasla")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Username");

                    b.HasKey("IdUzytkownika");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Data.Data.Magazyn.UzytkownikRola", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserRoleId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdRoli")
                        .HasColumnType("int")
                        .HasColumnName("RoleId");

                    b.Property<int>("IdUzytkownika")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("IdRoli");

                    b.HasIndex("IdUzytkownika", "IdRoli")
                        .IsUnique();

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Data.Data.Magazyn.Kategoria", b =>
                {
                    b.HasOne("Data.Data.Magazyn.Kategoria", "NadrzednaKategoria")
                        .WithMany("Podkategorie")
                        .HasForeignKey("IdNadrzednejKategorii")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NadrzednaKategoria");
                });

            modelBuilder.Entity("Data.Data.Magazyn.Lokacja", b =>
                {
                    b.HasOne("Data.Data.Magazyn.Magazyn", "Magazyn")
                        .WithMany("Lokacje")
                        .HasForeignKey("IdMagazynu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Magazyn");
                });

            modelBuilder.Entity("Data.Data.Magazyn.Produkt", b =>
                {
                    b.HasOne("Data.Data.Magazyn.Kategoria", "Kategoria")
                        .WithMany("Produkty")
                        .HasForeignKey("IdKategorii")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategoria");
                });

            modelBuilder.Entity("Data.Data.Magazyn.RuchMagazynowy", b =>
                {
                    b.HasOne("Data.Data.Magazyn.Lokacja", "LokacjaDo")
                        .WithMany()
                        .HasForeignKey("IdLokacjiDo");

                    b.HasOne("Data.Data.Magazyn.Lokacja", "LokacjaZ")
                        .WithMany()
                        .HasForeignKey("IdLokacjiZ");

                    b.HasOne("Data.Data.Magazyn.Produkt", "Produkt")
                        .WithMany()
                        .HasForeignKey("IdProduktu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Data.Magazyn.Uzytkownik", "Uzytkownik")
                        .WithMany()
                        .HasForeignKey("IdUzytkownika");

                    b.Navigation("LokacjaDo");

                    b.Navigation("LokacjaZ");

                    b.Navigation("Produkt");

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("Data.Data.Magazyn.StanMagazynowy", b =>
                {
                    b.HasOne("Data.Data.Magazyn.Lokacja", "Lokacja")
                        .WithMany("Stany")
                        .HasForeignKey("IdLokacji")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Data.Magazyn.Produkt", "Produkt")
                        .WithMany()
                        .HasForeignKey("IdProduktu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lokacja");

                    b.Navigation("Produkt");
                });

            modelBuilder.Entity("Data.Data.Magazyn.UzytkownikRola", b =>
                {
                    b.HasOne("Data.Data.Magazyn.Rola", "Rola")
                        .WithMany("Uzytkownicy")
                        .HasForeignKey("IdRoli")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Data.Magazyn.Uzytkownik", "Uzytkownik")
                        .WithMany("RoleUzytkownika")
                        .HasForeignKey("IdUzytkownika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rola");

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("Data.Data.Magazyn.Kategoria", b =>
                {
                    b.Navigation("Podkategorie");

                    b.Navigation("Produkty");
                });

            modelBuilder.Entity("Data.Data.Magazyn.Lokacja", b =>
                {
                    b.Navigation("Stany");
                });

            modelBuilder.Entity("Data.Data.Magazyn.Magazyn", b =>
                {
                    b.Navigation("Lokacje");
                });

            modelBuilder.Entity("Data.Data.Magazyn.Rola", b =>
                {
                    b.Navigation("Uzytkownicy");
                });

            modelBuilder.Entity("Data.Data.Magazyn.Uzytkownik", b =>
                {
                    b.Navigation("RoleUzytkownika");
                });
#pragma warning restore 612, 618
        }
    }
}
